steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_TRANSLATE_NAME}:${_TRANSLATE_VERSION}',
           '-t', 'gcr.io/$PROJECT_ID/${_TRANSLATE_NAME}',
           '.']
substitutions:
  _TRANSLATE_VERSION: 1.0.0
  _TRANSLATE_NAME: translate-service 

images:
  - 'gcr.io/$PROJECT_ID/${_TRANSLATE_NAME}:latest'
  - 'gcr.io/$PROJECT_ID/${_TRANSLATE_NAME}:${_TRANSLATE_VERSION}'
tags: ['googleapis', 'translate']
